name: PRAT Build - Image

on:
  push:
    paths:
      - 'Dockerfile'
  schedule:
    - cron: '15 21 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prat:$(date +%s)
